// src/app/pages/products/components/form/product.form.component.ts
import {
    NgClass,
} from '@angular/common';
import {
    AfterViewInit,
    Component,
    ElementRef,
    EventEmitter,
    Input,
    Output,
    ViewChild,
} from '@angular/core';
import {
    AbstractControl,
    FormBuilder,
    FormControl,
    FormGroup,
    ReactiveFormsModule,
    Validators,
} from '@angular/forms';

import {
    ProductResponse,
    ProductRequest,
    ProductsService,
} from '../../../../services';
import {
    toTrim,
} from '../../../../string';

@Component({
    standalone: true,
    selector: 'product-form',
    imports: [
        ReactiveFormsModule,
        NgClass,
    ],
    templateUrl: './product.form.component.html'
})
export class ProductFormComponent implements AfterViewInit {
    public readonly _noOfFields: number[] = [...Array(3).keys()];

    @Input('id')
    public id: string | null = null;

    @ViewChild('focusOn')
    public focusOn: ElementRef<HTMLInputElement> | undefined;
    
    @Output('onClose')
    public onClose: EventEmitter<void> = new EventEmitter();
    
    public isLoading: boolean = true;
    public mainFormGroup: FormGroup;
    public errorMessage: string = '';
    public isSubmitted: boolean = false;

    constructor(
        private readonly _formBuilder: FormBuilder,
        private readonly _productsService: ProductsService,
    ) {
        this.mainFormGroup = this._formBuilder.group({});
    }

    ngAfterViewInit(
    ): void {
        setTimeout(
            () => {
                this.isLoading = true;

                this.setupFormGroup();
            },
            500,
        );
    }

    private async setupFormGroup(
    ): Promise<void> {
        const product: ProductResponse = await this.load();
        const productPrice: string = product.id === 'NEW' ? '' : product.price.toString();

        this.mainFormGroup = this._formBuilder.group({
            name: new FormControl(product.name, [Validators.required, Validators.minLength(3)]),
            quantity: new FormControl(product.quantity, [Validators.required, Validators.min(10), Validators.max(1000)]),
            price: new FormControl(productPrice, [Validators.required, Validators.min(10), Validators.max(2000)]),
            sort: new FormControl(product.sort, [Validators.required, Validators.min(100), Validators.max(2000)]),
        });

        this.isLoading = false;

        setTimeout(
            () => {
                this.focusOn?.nativeElement.focus();
            },
            500,
        );
    }

    private async load(
    ): Promise<ProductResponse> {
        if (this.hasValidId) {
            const product: ProductResponse = await this._productsService.getById(this.id!);

            return product;
        }

        return {
            id: 'NEW',
            name: '',
            quantity: 500,
            price: -1,
            sort: 100,
            hasOrders: false,
        };
    }

    public get hasValidId(
    ): boolean {
        return this.id !== null && this.id!.length > 0;
    }

    public get hasError(
    ): boolean {
        return this.errorMessage.length > 0;
    }

    public get mainFormGroupControls(
    ): { [key: string]: AbstractControl } {
        return this.mainFormGroup.controls;
    }

    public onCancelClicked(
    ): void {
        this.onClose.emit();
    }

    public async onSubmitClicked(
    ): Promise<void> {
        this.isSubmitted = true;

        try {
            const request: ProductRequest = {
                name: toTrim(this.mainFormGroupControls.name.value),
                quantity: this.mainFormGroupControls.quantity.value,
                price: this.mainFormGroupControls.price.value,
                sort: this.mainFormGroupControls.sort.value,
            };

            if (this.hasValidId) {
                await this._productsService.modify(this.id!, request);
            } else {
                await this._productsService.add(request);
            }

            this.onClose.emit();
        } catch (error) {
            const err: Error = error as Error;
            this.errorMessage = err.message;
            this.isSubmitted = false;
        }
    }
};
<div class="offcanvas offcanvas-end show" tabindex="-1" aria-modal="true" role="dialog">
    <div class="offcanvas-header text-bg-primary">
        @if (hasValidId) {
            <h5 class="offcanvas-title">Edit Product</h5>
        }
        @else {
            <h5 class="offcanvas-title">Add Product</h5>
        }
    </div>

    <div class="offcanvas-body">
        @if (isLoading) {
            <div class="placeholder-glow">
                @for (item of _noOfFields; track $index) {
                    <div class="mb-3">
                        <label class="form-label col-5 placeholder"></label>
                        
                        <span class="form-control col-12 placeholder"></span>
                    </div>
                }
    
                <button type="button" disabled class="btn btn-primary col-4 placeholder">
                </button>
    
                <button type="button" disabled class="btn btn-secondary ms-2 col-4 placeholder">
                </button>
            </div>
        }
        @else {
            @if (hasError) {
                <div class="alert alert-danger" role="alert">
                    <div class="row">
                        <div class="col-1">
                            <i class="bi bi-patch-exclamation"></i>
                        </div>
            
                        <div class="col-11">
                            {{ errorMessage }}
                        </div>
                    </div>
                </div>
            }

            <div [formGroup]="mainFormGroup">
                <fieldset>
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>

                        <input type="text" formControlName="name" id="name" #focusOn
                            class="form-control" [ngClass]="{ 'is-invalid': mainFormGroupControls.name.errors, 'is-valid': mainFormGroupControls.name.valid }">

                        @if (mainFormGroupControls.name.errors) {
                            <div class="invalid-feedback">
                                @if (mainFormGroupControls.name.errors.required) {
                                    <div>Name is required</div>
                                }
                                @else if (mainFormGroupControls.name.errors.minlength) {
                                    <div>Name at least should be 3 characters</div>
                                }
                            </div>
                        }
                    </div>

                    <div class="mb-3">
                        <label for="price" class="form-label">Price</label>

                        <div class="input-group has-validation">
                            <input type="number" formControlName="price" id="price"
                                class="form-control" [ngClass]="{ 'is-invalid': mainFormGroupControls.price.errors, 'is-valid': mainFormGroupControls.price.valid }"
                                inputmode="numeric" min="1">
                            
                            <span class="input-group-text">₹</span>
                            
                            @if (mainFormGroupControls.price.errors) {
                                <div class="invalid-feedback">
                                    @if (mainFormGroupControls.price.errors.required) {
                                        <div>Price is required</div>
                                    }
                                    @else if (mainFormGroupControls.price.errors.min || mainFormGroupControls.price.errors.max) {
                                        <div>Price should be between 10 and 2000</div>
                                    }
                                </div>
                            }
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="quantity" class="form-label">Quantity</label>

                        <div class="input-group has-validation">
                            <input type="number" formControlName="quantity" id="quantity"
                                class="form-control" [ngClass]="{ 'is-invalid': mainFormGroupControls.quantity.errors, 'is-valid': mainFormGroupControls.quantity.valid }"
                                inputmode="numeric" min="10">
                            
                            <span class="input-group-text">grams</span>
                            
                            @if (mainFormGroupControls.quantity.errors) {
                                <div class="invalid-feedback">
                                    @if (mainFormGroupControls.quantity.errors.required) {
                                        <div>Quantity is required</div>
                                    }
                                    @else if (mainFormGroupControls.quantity.errors.min || mainFormGroupControls.quantity.errors.max) {
                                        <div>Quantity should be between 10 and 1000</div>
                                    }
                                </div>
                            }
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="sort" class="form-label">Order</label>

                        <input type="number" formControlName="sort" id="sort"
                            class="form-control" [ngClass]="{ 'is-invalid': mainFormGroupControls.sort.errors, 'is-valid': mainFormGroupControls.sort.valid }"
                            inputmode="numeric" min="100" step="10">
                        
                        @if (mainFormGroupControls.sort.errors) {
                            <div class="invalid-feedback">
                                @if (mainFormGroupControls.sort.errors.required) {
                                    <div>Sort is required</div>
                                }
                                @else if (mainFormGroupControls.sort.errors.min || mainFormGroupControls.sort.errors.max) {
                                    <div>Sort should be between 100 and 2000</div>
                                }
                            </div>
                        }
                    </div>
                </fieldset>

                <button type="submit" (click)="onSubmitClicked()" [disabled]="mainFormGroup.invalid" class="btn btn-primary">
                    @if (isSubmitted) {
                        <div class="spinner-border spinner-border-sm" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    }
                    @else {
                        <i class="bi bi-hdd"></i>
                    }
                    <span class="ms-2">Save</span>
                </button>

                <button type="button" (click)="onCancelClicked()" class="btn btn-outline-secondary ms-2">
                    <i class="bi bi-x-lg"></i>
                    <span class="ms-2">Cancel</span>
                </button>
            </div>
        }
    </div>
</div>
<div class="offcanvas-backdrop fade show"></div>

// React.v18/src/pages/products/components/ProductFormComponent.tsx
import {
    useEffect,
    useState,
} from 'react';
import {
    FieldValues,
    useForm,
} from 'react-hook-form';

import {
    AlertComponent,
    LoadingFormComponent,
} from '../../../components';
import {
    isNotNullOrEmpty,
} from '../../../Extensions';
import {
    ProductRequest,
    ProductResponse,
    ServiceProvider,
    useServiceContext,
} from '../../../services';

type ProductForm = {
    name: string | null,
    price: number | null,
    quantity: number | null,
    sort: number | null,
};

type ProductFormProps = {
    product: ProductResponse | null,
    onClose: () => void,
};

export const ProductFormComponent = (
    props: ProductFormProps
): JSX.Element => {
    const serviceProvider: ServiceProvider = useServiceContext()!;
    
    const [ errorMessage, setErrorMessage ] = useState<string>('');

    const {
        register,
        handleSubmit,
        formState: {
            isDirty,
            isSubmitting,
            isLoading,
            isValid,
            errors,
        },
        setFocus,
        trigger,
    } = useForm<ProductForm>({
        mode: 'all',
        defaultValues: {
            name: props.product?.name,
            price: props.product?.price,
            quantity: props.product?.quantity ?? 500,
            sort: props.product?.sort ?? 100,
        }
    });

    function hasValidProduct(
    ): boolean {
        return props.product !== null;
    };

    function hasError(
    ): boolean {
        return isNotNullOrEmpty(errorMessage);
    };

    useEffect(
        () => {
            const asyncUseEffect = async (): Promise<void> => {
                await trigger();

                setFocus("name");
            };

            asyncUseEffect();
        },
        [
            setFocus,
            trigger,
        ]
    );

    function onCancelClicked(
    ): void {
        props.onClose();
    };

    async function onSubmitClicked(
        fieldValues: FieldValues,
    ): Promise<void> {
        try {
            const request: ProductRequest = {
                name: fieldValues.name,
                quantity: fieldValues.quantity,
                price: fieldValues.price,
                sort: fieldValues.sort,
            };

            if (hasValidProduct()) {
                await serviceProvider.products.modify(props.product!.id, request);
            } else {
                await serviceProvider.products.add(request);
            }

            props.onClose();
        } catch (error) {
            const err: Error = error as Error;
            setErrorMessage(err.message);
        }
    };

    return (
        <>
            <div className="offcanvas offcanvas-end show" tabIndex={-1} aria-modal="true" role="dialog">
                <div className="offcanvas-header text-bg-primary">
                    <h5 className="offcanvas-title">
                        {
                            hasValidProduct() &&
                                <span className="me-2">Edit</span>
                        }
                        {
                            !hasValidProduct() &&
                                <span className="me-2">Add</span>
                        }
                        Product
                    </h5>
                </div>

                <div className="offcanvas-body">
                    {
                        isLoading &&
                            <LoadingFormComponent
                                noOfFields={4}
                            />
                    }

                    {
                        hasError() &&
                            <AlertComponent
                                message={errorMessage}
                                icon="exclamation"
                                type="danger"
                                onOffcanvas={true} />
                    }

                    {
                        !isLoading &&
                            <form onSubmit={handleSubmit(onSubmitClicked)}>
                                <fieldset>
                                    <div className="mb-3">
                                        <label htmlFor="name" className="form-label">Name</label>

                                        <input type="text" id="name"
                                            className={`form-control ${errors.name ? 'is-invalid' : 'is-valid'}`}
                                            {
                                                ...register(
                                                    'name', {
                                                        required: {
                                                            value: true,
                                                            message: 'Name is required',
                                                        },
                                                        minLength: {
                                                            value: 3,
                                                            message: 'Name at least should be 3 characters',
                                                        },
                                                    }
                                                )
                                            } />
                                        
                                        {
                                            errors.name && (
                                                <div className="invalid-feedback">
                                                    { errors.name.message }
                                                </div>
                                            )
                                        }
                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="price" className="form-label">Price</label>

                                        <div className="input-group has-validation">
                                            <input type="number" id="price" inputMode="numeric" min="1"
                                                className={`form-control ${errors.price ? 'is-invalid' : 'is-valid'}`}
                                                {
                                                    ...register(
                                                        'price', {
                                                            required: {
                                                                value: true,
                                                                message: 'Price is required',
                                                            },
                                                            min: {
                                                                value: 10,
                                                                message: 'Price should be between 10 and 2000',
                                                            },
                                                            max: {
                                                                value: 2000,
                                                                message: 'Price should be between 10 and 2000',
                                                            },
                                                            valueAsNumber: true,
                                                        }
                                                    )
                                                } />
                                            
                                            <span className="input-group-text">₹</span>

                                            {
                                                errors.price && (
                                                    <div className="invalid-feedback">
                                                        { errors.price.message }
                                                    </div>
                                                )
                                            }
                                        </div>
                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="quantity" className="form-label">Quantity</label>

                                        <div className="input-group has-validation">
                                            <input type="number" id="quantity" inputMode="numeric" min="10"
                                                className={`form-control ${errors.quantity ? 'is-invalid' : 'is-valid'}`}
                                                {
                                                    ...register(
                                                        'quantity', {
                                                            required: {
                                                                value: true,
                                                                message: 'Quantity is required',
                                                            },
                                                            min: {
                                                                value: 10,
                                                                message: 'Quantity should be between 10 and 1000',
                                                            },
                                                            max: {
                                                                value: 1000,
                                                                message: 'Quantity should be between 10 and 1000',
                                                            },
                                                            valueAsNumber: true,
                                                        }
                                                    )
                                                } />
                                            
                                            <span className="input-group-text">grams</span>

                                            {
                                                errors.quantity && (
                                                    <div className="invalid-feedback">
                                                        { errors.quantity.message }
                                                    </div>
                                                )
                                            }
                                        </div>
                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="sort" className="form-label">Order</label>

                                        <input type="number" id="sort" inputMode="numeric" min="100" step="10"
                                            className={`form-control ${errors.sort ? 'is-invalid' : 'is-valid'}`}
                                            {
                                                ...register(
                                                    'sort', {
                                                        required: {
                                                            value: true,
                                                            message: 'Order is required',
                                                        },
                                                        min: {
                                                            value: 10,
                                                            message: 'Order should be between 100 and 2000',
                                                        },
                                                        max: {
                                                            value: 1000,
                                                            message: 'Order should be between 100 and 2000',
                                                        },
                                                        valueAsNumber: true,
                                                    }
                                                )
                                            } />
                                        
                                        {
                                            errors.sort && (
                                                <div className="invalid-feedback">
                                                    { errors.sort.message }
                                                </div>
                                            )
                                        }
                                    </div>
                                </fieldset>

                                <button type="submit" disabled={!isDirty || !isValid || isSubmitting} className="btn btn-primary" title="Save Product">
                                    {
                                        isSubmitting &&
                                            <div className="spinner-border spinner-border-sm" role="status">
                                                <span className="visually-hidden">Loading...</span>
                                            </div>
                                    }

                                    {
                                        !isSubmitting &&
                                            <i className="bi bi-hdd"></i>
                                    }

                                    <span className="ms-2">Save</span>
                                </button>

                                <button type="reset" onClick={onCancelClicked} disabled={isSubmitting} className="btn btn-outline-secondary ms-2" title="Go back to Products">
                                    <i className="bi bi-x-lg"></i>
                                    <span className="ms-2">Cancel</span>
                                </button>
                            </form>
                    }
                </div>
            </div>

            <div className="offcanvas-backdrop fade show"></div>
        </>
    );
};

export default ProductFormComponent;
