// src/app/components/footer/footer.component.ts
import {
    Component,
} from '@angular/core';

@Component({
    standalone: true,
    selector: 'app-footer',
    templateUrl: './footer.component.html'
})
export class FooterComponent {
    public readonly currentYear: number = new Date().getFullYear();
};
<footer class="text-center mt-5 py-5 border-top">
    {{ currentYear }} &copy; Mithay Samiti
</footer>

// React.v18/src/components/FooterComponent.tsx
export const FooterComponent = (
): JSX.Element => {
    const currentYear: number = new Date().getFullYear();

    return (
        <footer className="text-center mt-5 py-5 border-top">
            { currentYear } &copy; iOrder Book - React v18
        </footer>
    );
};

export default FooterComponent;
