// React.v18/src/pages/orders/components/OrderProductFormComponent.tsx
import {
    useEffect,
    useState,
} from 'react';
import {
    FieldValues,
    useForm,
} from 'react-hook-form';

import {
    LoadingFormComponent,
} from '../../../components';
import {
    OrderProductResponse,
    ProductResponse,
    ServiceProvider,
    useServiceContext,
} from '../../../services';

type OrderProductForm = {
    productId: string | null,
    numberOfPackets: number | null,
};

type OrderProductFormProps = {
    orderProduct: OrderProductResponse | null,
    onClose: (orderProduct: OrderProductResponse | null) => void,
};

export const OrderProductFormComponent = (
    props: OrderProductFormProps,
): JSX.Element => {
    const serviceProvider: ServiceProvider = useServiceContext()!;

    const [ products, setProducts ] = useState<ProductResponse[]>([]);

    const {
        register,
        handleSubmit,
        formState: {
            isDirty,
            isLoading,
            isSubmitting,
            isValid,
            errors,
        },
        setFocus,
        trigger,
        setValue,
    } = useForm<OrderProductForm>({
        mode: 'all',
        defaultValues: {
            productId: null,
            numberOfPackets: 1,
        }
    });

    function hasValidOrderProduct(
    ): boolean {
        return null !== props.orderProduct;
    };

    useEffect(
        () => {
            const asyncUseEffect = async (): Promise<void> => {
                const products: ProductResponse[] = await serviceProvider.products.getAll();
                setProducts(products);

                if (hasValidOrderProduct()) {
                    setValue(
                        'productId',
                        props.orderProduct!.product.id, {
                            shouldValidate: true,
                        }
                    );
                    setValue(
                        'numberOfPackets',
                        props.orderProduct!.numberOfPackets, {
                            shouldValidate: true,
                        }
                    );
                }

                await trigger();

                setFocus('productId');
            };

            asyncUseEffect();
        },
        [
            setFocus,
            trigger,
        ]
    );

    function onCancelClicked(
    ): void {
        props.onClose(null);
    };

    function onSubmitClicked(
        fieldValues: FieldValues,
    ): void {
        const selectedProductId: string = fieldValues.productId;
        const numberOfPackets: number = fieldValues.numberOfPackets;
        const product: ProductResponse = products
            .findLast(
                (value) => value.id === selectedProductId!
            )!;
        const orderProduct: OrderProductResponse = {
            product: product,
            numberOfPackets: numberOfPackets,
            amount: numberOfPackets * product.price,
        };

        props.onClose(orderProduct);
    };

    return (
        <>
            <div className="offcanvas offcanvas-end show" tabIndex={-1} aria-modal="true" role="dialog">
                <div className="offcanvas-header text-bg-primary">
                    <h5 className="offcanvas-title">
                        {
                            hasValidOrderProduct() &&
                                <span className="me-2">Edit</span>
                        }
                        {
                            !hasValidOrderProduct() &&
                                <span className="me-2">Add</span>
                        }
                        Product
                    </h5>
                </div>

                <div className="offcanvas-body">
                    
                    {
                        isLoading &&
                            <LoadingFormComponent noOfFields={4} />
                    }

                    {
                        !isLoading &&
                            <form onSubmit={handleSubmit(onSubmitClicked)}>
                                <fieldset>
                                    <div className="mb-3">
                                        <label htmlFor="productId" className="form-label">Product</label>

                                        <select id="productId"
                                            className={`form-control ${errors.productId ? 'is-invalid' : 'is-valid'}`}
                                            {
                                                ...register(
                                                    `productId`, {
                                                        required: {
                                                            value: true,
                                                            message: 'Product is required',
                                                        },
                                                    }
                                                )
                                            }>

                                            {
                                                !hasValidOrderProduct() &&
                                                    <option value="" disabled>--- Select Product ---</option>
                                            }

                                            {
                                                products
                                                    .map(
                                                        (product: ProductResponse) => {
                                                            return (
                                                                <option key={product.id} value={product.id}>{ product.name }</option>
                                                            );
                                                        }
                                                    )
                                            }
                                        </select>
                                        
                                        {
                                            errors.productId && (
                                                <div className="invalid-feedback">
                                                    { errors.productId.message }
                                                </div>
                                            )
                                        }
                                    </div>

                                    <div className="mb-3">
                                        <label htmlFor="numberOfPackets" className="form-label">Number of Packets</label>

                                        <input type="number" id="numberOfPackets" inputMode="numeric" min="1"
                                            className={`form-control ${errors.numberOfPackets ? 'is-invalid' : 'is-valid'}`}
                                            {
                                                ...register(
                                                    'numberOfPackets', {
                                                        required: {
                                                            value: true,
                                                            message: 'Number of Packets is required',
                                                        },
                                                        min: {
                                                            value: 1,
                                                            message: 'Number of Packets should be at least 1',
                                                        },
                                                        valueAsNumber: true,
                                                    }
                                                )
                                            } />

                                        {
                                            errors.numberOfPackets && (
                                                <div className="invalid-feedback">
                                                    { errors.numberOfPackets.message }
                                                </div>
                                            )
                                        }
                                    </div>
                                </fieldset>

                                <button type="submit" disabled={!isDirty || !isValid || isSubmitting} className="btn btn-primary">
                                    {
                                        isSubmitting &&
                                            <div className="spinner-border spinner-border-sm" role="status">
                                                <span className="visually-hidden">Loading...</span>
                                            </div>
                                    }

                                    {
                                        !isSubmitting &&
                                            <i className="bi bi-hdd"></i>
                                    }

                                    <span className="ms-2">Save</span>
                                </button>

                                <button type="reset" onClick={onCancelClicked} disabled={isSubmitting} className="btn btn-outline-secondary ms-2">
                                    <i className="bi bi-x-lg"></i>
                                    <span className="ms-2">Cancel</span>
                                </button>
                            </form>
                    }
                </div>
            </div>

            <div className="offcanvas-backdrop fade show"></div>
        </>
    );
};

export default OrderProductFormComponent;

// src/app/pages/orders/components/order.product.form/order.product.form.component.ts
import {
    NgClass,
} from '@angular/common';
import {
    AfterViewInit,
    Component,
    ElementRef,
    EventEmitter,
    Input,
    input,
    Output,
    ViewChild,
} from '@angular/core';
import {
    AbstractControl,
    FormBuilder,
    FormControl,
    FormGroup,
    ReactiveFormsModule,
    Validators,
} from '@angular/forms';

import {
    OrderProductResponse,
    ProductModel,
    ProductResponse,
    ProductsService,
} from '../../../../services';

@Component({
    standalone: true,
    selector: 'order-product-form',
    imports: [
        ReactiveFormsModule,
        NgClass,
    ],
    templateUrl: './order.product.form.component.html'
})
export class OrderProductFormComponent implements AfterViewInit {
    public readonly _noOfFields: number[] = [...Array(3).keys()];

    @Input('orderProduct')
    public orderProduct: OrderProductResponse | null = null;
    
    @Output('onClose')
    public onClose: EventEmitter<OrderProductResponse | null> = new EventEmitter();

    @ViewChild('focusOn')
    public focusOn: ElementRef<HTMLInputElement> | undefined;
    
    public isLoading: boolean = true;
    public products: ProductResponse[] = [];
    public product: ProductModel | null = null;
    public mainFormGroup: FormGroup;
    public errorMessage: string = '';

    constructor(
        private readonly _formBuilder: FormBuilder,
        private readonly _productsService: ProductsService,
    ) {
        this.mainFormGroup = this._formBuilder.group({});
    }

    ngAfterViewInit(
    ): void {
        setTimeout(
            () => {
                this.isLoading = true;

                this.setupFormGroup();
            },
            500,
        );
    }

    private async setupFormGroup(
    ): Promise<void> {
        this.products = await this._productsService.getAll();

        if (this.orderProduct === null) {
            this.product = null;
            this.mainFormGroup = this._formBuilder.group({
                productId: new FormControl('', [Validators.required]),
                quantity: new FormControl('', [Validators.required, Validators.min(1)]),
            });
        } else {
            const indexOfProdct: number = this.products
                .findIndex(
                    (value) => value.id == this.orderProduct!.product.id
                );
            
            this.product = this.products[indexOfProdct];
            this.mainFormGroup = this._formBuilder.group({
                productId: new FormControl(indexOfProdct, [Validators.required]),
                quantity: new FormControl(this.orderProduct.numberOfPackets, [Validators.required, Validators.min(1)]),
            });
        }

        this.isLoading = false;

        setTimeout(
            () => {
                this.focusOn?.nativeElement.focus();
            },
            500,
        );
    }

    public get hasError(
    ): boolean {
        return this.errorMessage.length > 0;
    }

    public get hasProduct(
    ): boolean {
        return this.product !== null;
    }

    public get amount(
    ): number {
        if (!this.hasProduct) {
            return 0;
        }

        return this.mainFormGroupControls.quantity.value * this.product!.price;
    }

    public get mainFormGroupControls(
    ): { [key: string]: AbstractControl } {
        return this.mainFormGroup.controls;
    }

    public onProductSelected(
        index: number,
    ): void {
        this.product = this.products[index];
    }

    public onCancelClicked(
    ): void {
        this.onClose.emit(null);
    }

    public onSubmitClicked(
    ): void {
        const orderProduct: OrderProductResponse = {
            product: this.product!,
            numberOfPackets: this.mainFormGroupControls.quantity.value,
            amount: this.mainFormGroupControls.quantity.value * this.product!.price,
        };

        this.onClose.emit(orderProduct);
    }
};
<div class="offcanvas offcanvas-end show" tabindex="-1" aria-modal="true" role="dialog">
    <div class="offcanvas-header text-bg-primary">
        @if (hasProduct) {
            <h5 class="offcanvas-title">Edit Product</h5>
        }
        @else {
            <h5 class="offcanvas-title">Add Product</h5>
        }
    </div>

    <div class="offcanvas-body">
        @if (isLoading) {
            <div class="placeholder-glow">
                @for (item of _noOfFields; track $index) {
                    <div class="mb-3">
                        <label class="form-label col-5 placeholder"></label>
                        
                        <span class="form-control col-12 placeholder"></span>
                    </div>
                }
    
                <button type="button" disabled class="btn btn-primary col-4 placeholder">
                </button>
    
                <button type="button" disabled class="btn btn-secondary ms-2 col-4 placeholder">
                </button>
            </div>
        }
        @else {
            @if (hasError) {
                <div class="alert alert-danger" role="alert">
                    <div class="row">
                        <div class="col-1">
                            <i class="bi bi-patch-exclamation"></i>
                        </div>
            
                        <div class="col-11">
                            {{ errorMessage }}
                        </div>
                    </div>
                </div>
            }
            @else {
                <div [formGroup]="mainFormGroup">
                    <fieldset>
                        <div class="mb-3">
                            <label for="productId" class="form-label">Product</label>

                            <select formControlName="productId" id="productId" #focusOn
                                class="form-select" [ngClass]="{ 'is-invalid': mainFormGroupControls.productId.errors, 'is-valid': mainFormGroupControls.productId.valid }"
                                (ngModelChange)="onProductSelected($event)">
                                @for (product of products; track $index) {
                                    <option [value]="$index">{{ product.name }}</option>
                                }
                            </select>

                            @if (mainFormGroupControls.productId.errors) {
                                <div class="invalid-feedback">
                                    @if (mainFormGroupControls.productId.errors.required) {
                                        <div>Product is required</div>
                                    }
                                </div>
                            }
                        </div>

                        <div class="row mb-3">
                            <div class="col-6">
                                <label class="form-label">Quantity</label>
                                
                                @if (hasProduct) {
                                    <span class="form-control-plaintext">{{ product?.quantity }} grams</span>
                                }
                                @else {
                                    <span class="form-control-plaintext"></span>
                                }
                            </div>

                            <div class="col-6">
                                <label class="form-label">Price</label>
                                
                                @if (hasProduct) {
                                    <span class="form-control-plaintext fw-bold text-primary">{{ product?.price }} ₹</span>
                                }
                                @else {
                                    <span class="form-control-plaintext"></span>
                                }
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="quantity" class="form-label">No of Packets</label>

                            <input type="number" formControlName="quantity" id="quantity"
                                class="form-control" [ngClass]="{ 'is-invalid': mainFormGroupControls.quantity.errors, 'is-valid': mainFormGroupControls.quantity.valid }"
                                min="1">

                            @if (mainFormGroupControls.quantity.errors) {
                                <div class="invalid-feedback">
                                    @if (mainFormGroupControls.quantity.errors.required) {
                                        <div>No of Packets is required</div>
                                    }

                                    @if (mainFormGroupControls.quantity.errors.min) {
                                        <div>No of Packets should be at least 1</div>
                                    }
                                </div>
                            }
                        </div>

                        <div class="mb-3">
                            <label class="form-label fw-bold">Amount</label>
                            
                            <span class="form-control-plaintext fw-bold text-primary">{{ amount }} ₹</span>
                        </div>
                    </fieldset>

                    <button type="submit" (click)="onSubmitClicked()" [disabled]="mainFormGroup.invalid" class="btn btn-primary">
                        <i class="bi bi-hdd"></i>
                        <span class="ms-2">Save</span>
                    </button>

                    <button type="button" (click)="onCancelClicked()" class="btn btn-outline-secondary ms-2">
                        <i class="bi bi-x-lg"></i>
                        <span class="ms-2">Cancel</span>
                    </button>
                </div>
            }
        }
    </div>
</div>
<div class="offcanvas-backdrop fade show"></div>
