// React.v18/src/pages/products/components/ProductDeleteComponent.tsx
import {
    useState,
} from 'react';

import {
    AlertComponent,
} from '../../../components';
import {
    isNotNullOrEmpty,
} from '../../../Extensions';
import {
    ProductResponse,
    ServiceProvider,
    useServiceContext,
} from '../../../services';

type ProductDeleteProps = {
    product: ProductResponse,
    onClose: () => void,
};

export const ProductDeleteComponent = (
    props: ProductDeleteProps
): JSX.Element => {
    const serviceProvider: ServiceProvider = useServiceContext()!;
    
    const [ errorMessage, setErrorMessage ] = useState<string>('');
    const [ isSubmitted, setIsSubmitted ] = useState<boolean>(false);

    function hasError(
    ): boolean {
        return isNotNullOrEmpty(errorMessage);
    }

    function onCancelClicked(
    ): void {
        props.onClose();
    };

    async function onDeleteClicked(
    ): Promise<void> {
        setIsSubmitted(true);

        try {
            await serviceProvider.products.delete(props.product.id);

            props.onClose();
        } catch (error) {
            const err: Error = error as Error;
            setErrorMessage(err.message);
            setIsSubmitted(false);
        }
    };

    return (
        <>
            <div className="offcanvas offcanvas-end show" tabIndex={-1} aria-modal="true" role="dialog">
                <div className="offcanvas-header text-bg-primary">
                    <h5 className="offcanvas-title">Delete Product</h5>
                </div>

                <div className="offcanvas-body">
                    <AlertComponent
                        message="Are you sure you want to delete Product?"
                        icon="question"
                        type="danger"
                        onOffcanvas={true} />

                    {
                        hasError() &&
                            <div className="alert alert-danger" role="alert">
                                <div className="row">
                                    <div className="col-1">
                                        <i className="bi bi-patch-exclamation"></i>
                                    </div>
                                    
                                    <div className="col-11">
                                        { errorMessage }
                                    </div>
                                </div>
                            </div>
                    }

                    <div className="mb-3">
                        <label className="fw-bold">Name</label>

                        <span className="form-control-plaintext">{ props.product.name }</span>
                    </div>

                    <div className="mb-3">
                        <label className="fw-bold">Price</label>

                        <span className="form-control-plaintext">{ props.product.price } ₹</span>
                    </div>

                    <div className="mb-3">
                        <label className="fw-bold">Quantity</label>

                        <span className="form-control-plaintext">{ props.product.quantity } grams</span>
                    </div>

                    <div className="mb-3">
                        <label className="fw-bold">Order</label>

                        <span className="form-control-plaintext">{ props.product.sort }</span>
                    </div>

                    <button type="submit" onClick={onDeleteClicked} disabled={isSubmitted} className="btn btn-danger" title="Delete Product">
                        {
                            isSubmitted &&
                                <div className="spinner-border spinner-border-sm" role="status">
                                    <span className="visually-hidden">Loading...</span>
                                </div>
                        }
                        {
                            !isSubmitted &&
                                <i className="bi bi-trash3"></i>
                        }

                        <span className="ms-2">Delete</span>
                    </button>

                    <button type="reset" onClick={onCancelClicked} disabled={isSubmitted} className="btn btn-outline-secondary ms-2" title="Go back to Products">
                        <i className="bi bi-x-lg"></i>
                        <span className="ms-2">Cancel</span>
                    </button>
                </div>
            </div>

            <div className="offcanvas-backdrop fade show"></div>
        </>
    );
};

export default ProductDeleteComponent;

// src/app/pages/products/components/delete/product.delete.component.ts
import {
    Component,
    EventEmitter,
    Input,
    OnInit,
    Output,
} from '@angular/core';

import {
    ProductModel,
    ProductsService,
} from '../../../../services';

@Component({
    standalone: true,
    selector: 'product-delete',
    templateUrl: './product.delete.component.html'
})
export class ProductDeleteComponent implements OnInit {
    public readonly _noOfFields: number[] = [...Array(3).keys()];

    @Input('id')
    public id: string | null = null;
    
    @Output('onClose')
    public onClose: EventEmitter<boolean> = new EventEmitter(false);
    
    public errorMessage: string = '';
    public isLoading: boolean = true;
    public product: ProductModel | null = null;

    constructor(
        private readonly _productsService: ProductsService,
    ) {
    }

    ngOnInit(
    ): void {
        setTimeout(
            () => {
                this.load();
            },
            500,
        );
    }

    private async load(
    ): Promise<void> {
        this.isLoading = true;
        
        this.product = await this._productsService.getById(this.id!);

        this.isLoading = false;
    }

    public get hasError(
    ): boolean {
        return this.errorMessage.length > 0;
    }

    public onCancelClicked(
    ): void {
        this.onClose.emit(false);
    }

    public async onDeleteClicked(
    ): Promise<void> {
        try {
            await this._productsService.delete(this.id!);

            this.onClose.emit(true);
        } catch (error) {
            const err: Error = error as Error;
            this.errorMessage = err.message;
        }
    }
};
<div class="offcanvas offcanvas-end show" tabindex="-1" aria-modal="true" role="dialog">
    <div class="offcanvas-header text-bg-danger">
        <h5 class="offcanvas-title">Delete Product</h5>
    </div>

    <div class="offcanvas-body">
        @if (isLoading) {
            <div class="placeholder-glow">
                @for (item of _noOfFields; track $index) {
                    <div class="mb-3">
                        <label class="form-label col-5 placeholder"></label>
                        
                        <span class="form-control col-12 placeholder"></span>
                    </div>
                }
    
                <button type="button" disabled class="btn btn-danger col-4 placeholder">
                </button>
    
                <button type="button" disabled class="btn btn-secondary ms-2 col-4 placeholder">
                </button>
            </div>
        }
        @else {
            <div class="alert alert-danger" role="alert">
                <div class="row">
                    <div class="col-1">
                        <i class="bi bi-patch-question"></i>
                    </div>

                    <div class="col-11">
                        Are you sure you want to delete Product?
                    </div>
                </div>
            </div>

            @if (hasError) {
                <div class="alert alert-danger" role="alert">
                    <div class="row">
                        <div class="col-1">
                            <i class="bi bi-patch-exclamation"></i>
                        </div>
            
                        <div class="col-11">
                            {{ errorMessage }}
                        </div>
                    </div>
                </div>
            }
    
            <div class="mb-3">
                <label class="fw-bold">Name</label>

                <span class="form-control-plaintext">{{ product!.name }}</span>
            </div>

            <div class="mb-3">
                <label class="fw-bold">Price</label>

                <span class="form-control-plaintext">{{ product!.price }} ₹</span>
            </div>

            <div class="mb-3">
                <label class="fw-bold">Quantity</label>

                <span class="form-control-plaintext">{{ product!.quantity }} grams</span>
            </div>

            <div class="mb-3">
                <label class="fw-bold">Order</label>

                <span class="form-control-plaintext">{{ product!.sort }} ₹</span>
            </div>

            <button type="submit" (click)="onDeleteClicked()" class="btn btn-danger">
                <i class="bi bi-hdd"></i>
                <span class="ms-2">Delete</span>
            </button>

            <button type="button" (click)="onCancelClicked()" class="btn btn-outline-secondary ms-2">
                <i class="bi bi-x-lg"></i>
                <span class="ms-2">Cancel</span>
            </button>
        }
    </div>
</div>
<div class="offcanvas-backdrop fade show"></div>
